alias: "Disk usage"
trigger:
  platform: numeric_state
  entity_id: sensor.disk_use_home
  above: 75
action:
  service: notify.pushbullet
  data:
    message: "Diskutrymme"
    title: "Över tröskel!"

