- action:
  - service: script.a_walk_in_the_night
  alias: Misc | Turn on light at night
  id: '1495643723115'
  trigger:
  - entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: 00:00:00
      before: 07:00:00
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_select.arm_debug
      state: Av
- action:
  - service: script.wake_up
  alias: Misc | Wake up in the morning
  id: '1495718802448'
  trigger:
  - hours: 6
    minutes: 0
    platform: time
    seconds: 0
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.patrik_iphone
      state: Home
    - condition: state
      entity_id: input_boolean.arm_wakeup_alarm
      state: 'on'
- action:
  - alias: ''
    data:
      message: "Juvelorkid\xE9 | vardagsrum"
      title: Please water me!
    service: notify.pushbullet
  alias: Flower | Vardagsrum | Juvelorkide
  id: '1495725269130'
  trigger:
  - below: '-1'
    entity_id: sensor.flower_1_moisture
    platform: numeric_state
- action:
  - alias: ''
    data:
      message: "Juvelorkid\xE9 | sovrum"
      title: Please water me!
    service: notify.pushbullet
  alias: Flower | Sovrum | Juvelorkide
  id: '1495725269131'
  trigger:
  - below: '10'
    entity_id: sensor.flower_2_moisture
    platform: numeric_state
- action:
  - alias: ''
    data:
      message: Chili | vardagsrum
      title: Please water me!
    service: notify.pushbullet
  alias: Flower | Vardagsrum | Chili
  id: '1495725269130'
  trigger:
  - below: '10'
    entity_id: sensor.flower_3_moisture
    platform: numeric_state
- action:
  - service: zwave.heal_network
  alias: Maintenance | Z-wave | Heal
  id: '1496477445434'
  trigger:
  - at: '2:31:00'
    platform: time
- action:
  - service: script.sonos_stereo_on
  alias: Sonos | Vardagsrum | Start stereo
  id: '1496478237477'
  trigger:
  - entity_id: media_player.vardagsrum_musik
    platform: state
    to: playing
- action:
  - service: script.sonos_stereo_off
  alias: Sonos | Vardagsrum | Stereo off (idle)
  id: '1496478400400'
  trigger:
  - entity_id: media_player.vardagsrum_musik
    platform: state
    to: idle
- action:
  - service: script.sonos_stereo_off
  alias: Sonos | Vardagsrum | Stereo off (pause)
  id: '1496478447779'
  trigger:
  - entity_id: media_player.vardagsrum_musik
    platform: state
    to: paused
- action:
  - service: shell_command.sonos_control_shuffle_off
  - service: shell_command.sonos_volume_8
  - service_template: 'shell_command.sonos_favorite_{{states.input_select.sonos_favorites.state.lower().replace("
      ", "").replace("-", "")}}

      '
  alias: Sonos | Play favorite
  id: '1496478661322'
  trigger:
  - entity_id: input_select.sonos_favorites
    platform: state
- action:
  - service: shell_command.sonos_control_shuffle_off
  - service: shell_command.sonos_volume_8
  - service_template: 'shell_command.sonos_playlist_{{states.input_select.sonos_playlist.state.lower().replace("
      ", "").replace("-", "")}}

      '
  alias: Sonos | Play playlist
  id: '1496478802292'
  trigger:
  - entity_id: input_select.sonos_playlist
    platform: state
- action:
  - service: notify.pushbullet
    data:
      message: "Diskutrymme \xF6ver tr\xF6skel"
      title: "D\xF6belnsgatan 89 | RPI3"
  alias: Maintenance | System | Disk space
  id: '1496517175891'
  trigger:
  - above: '75'
    entity_id: sensor.disk_use_home
    platform: numeric_state
- action:
  - service: script.arrive_home_anytime
  alias: Enter/exit | Arrive home
  id: '1496517346021'
  trigger:
  - entity_id: device_tracker.patrik_iphone
    from: Away
    platform: state
    to: Home
- action:
  - service: script.left_home
  alias: Enter/exit | Left home
  id: '1496517407855'
  trigger:
  - entity_id: device_tracker.patrik_iphone
    from: Home
    platform: state
    to: Away
- action:
  - service: script.arrive_home
  alias: Enter/exit | Home from work
  id: '1496517463812'
  trigger:
  - entity_id: device_tracker.patrik_iphone
    from: Away
    platform: state
    to: Home
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '15:00:00'
      before: '23:00:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_select.arm_debug
      state: Av

- action:
  - entity_id: scene.ceiling_at_home
    service: scene.turn_on
  alias: "Lights | Taklampor p\xE5"
  id: '1497121665496'
  trigger:
  - entity_id: switch.remote_2_on2
    platform: state
    to: 'on'
- action:
  - entity_id: light.sovrumstak
    service: light.turn_on
  alias: Floorplan | Sovrumstak | On
  id: '1500802730811'
  trigger:
  - entity_id: input_boolean.light_sovrumstak
    platform: state
    to: 'on'
- action:
  - entity_id: light.sovrumstak
    service: light.turn_off
  alias: Floorplan | Sovrumstak | Off
  id: '1500802730812'
  trigger:
  - entity_id: input_boolean.light_sovrumstak
    platform: state
    to: 'off'
- action:
  - entity_id: light.kokslampa
    service: light.turn_on
  alias: Floorplan | Kok | On
  id: '1500802730813'
  trigger:
  - entity_id: input_boolean.light_kokslampa
    platform: state
    to: 'on'
- action:
  - entity_id: light.kokslampa
    service: light.turn_off
  alias: Floorplan | Kok | Off
  id: '1500802730814'
  trigger:
  - entity_id: input_boolean.light_kokslampa
    platform: state
    to: 'off'
- action:
  - entity_id: light.vardagsrum
    service: light.turn_on
  alias: Floorplan | Vardagsrum | On
  id: '1500802730815'
  trigger:
  - entity_id: input_boolean.light_vardagsrum
    platform: state
    to: 'on'
- action:
  - entity_id: light.vardagsrum
    service: light.turn_off
  alias: Floorplan | Vardagsrum | Off
  id: '1500802730816'
  trigger:
  - entity_id: input_boolean.light_vardagsrum
    platform: state
    to: 'off'
- action:
  - entity_id: group.hall_taklampa
    service: light.turn_on
  alias: Floorplan | Taklampa hall | On
  id: '1500802730816'
  trigger:
  - entity_id: input_boolean.group_hall_taklampa
    platform: state
    to: 'on'
- action:
  - entity_id: group.hall_taklampa
    service: light.turn_off
  alias: Floorplan | Taklampa hall | Off
  id: '1500802730817'
  trigger:
  - entity_id: input_boolean.group_hall_taklampa
    platform: state
    to: 'off'

### Toogle floorplan light areas
- alias: Floorplan | Sovrumstak | Initiate | On
  id: '1500802730818'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: light.sovrumstak
      state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.light_sovrumstak

- alias: Floorplan | Sovrumstak | Initiate | Off
  id: '1500802730819'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: light.sovrumstak
      state: 'off'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.light_sovrumstak


- alias: Floorplan | Kok | Initiate | On
  id: '1500802730820'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: light.kokslampa
      state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.light_kokslampa

- alias: Floorplan | Kok | Initiate | Off
  id: '1500802730821'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: light.kokslampa
      state: 'off'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.light_kokslampa


- alias: Floorplan | Vardagsrum | Initiate | On
  id: '1500802730822'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: light.vardagsrum
      state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.light_vardagsrum

- alias: Floorplan | Vardagsrum | Initiate | Off
  id: '1500802730823'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: light.vardagsrum
      state: 'off'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.light_vardagsrum


- alias: Floorplan | Hall taklampa | Initiate | On
  id: '1500802730824'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: group.hall_taklampa
      state: 'on'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.group_hall_taklampa

- alias: Floorplan | Hall taklampa | Initiate | Off
  id: '1500802730825'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: group.hall_taklampa
      state: 'off'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.group_hall_taklampa
