- action:
  - service: script.a_walk_in_the_night
  alias: Turn on light at night
  id: '1495643723115'
  trigger:
  - entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_16_0
    platform: state
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: 00:00:00
      before: 07:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_select.arm_debug
      state: Av
- action:
  - service: script.wake_up
  alias: Wake up in the morning
  id: '1495718802448'
  trigger:
    platform: time
    hours: 6
    minutes: 0
    seconds: 0
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.patrik_iphone
      state: Home
    - condition: state
      entity_id: input_select.arm_wakeup_alarm
      state: "P\xE5"
- action:
  - alias: ''
    data:
      message: "Juvelorkidé | vardagsrum"
      title: "Please water me!"
    service: notify.pushbullet
  alias: Flower | Vardagsrum | Juvelorkide
  id: '1495725269130'
  trigger:
  - below: '10'
    entity_id: sensor.flower_1_moisture
    platform: numeric_state
- action:
  - alias: ''
    data:
      message: "Juvelorkidé | vardagsrum"
      title: "Please water me!"
    service: notify.pushbullet
  alias: Flower | Sovrum | Juvelorkide
  id: '1495725269131'
  trigger:
  - below: '10'
    entity_id: sensor.flower_2_moisture
    platform: numeric_state
- action:
  - alias: ''
    data:
      message: "Chili | vardagsrum"
      title: "Please water me!"
    service: notify.pushbullet
  alias: Flower | Vardagsrum | Chili
  id: '1495725269130'
  trigger:
  - below: '10'
    entity_id: sensor.flower_3_moisture
    platform: numeric_state
