- action:
  - service: script.a_walk_in_the_night
  alias: Misc | Turn on light at night
  id: '1495643723115'
  trigger:
  - entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_16_0
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - after: 00:00:00
      before: 07:00:00
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_select.arm_debug
      state: Av
- action:
  - service: script.wake_up
  alias: Misc | Wake up in the morning
  id: '1495718802448'
  trigger:
  - hours: 6
    minutes: 0
    platform: time
    seconds: 0
  condition:
  - condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: device_tracker.patrik_iphone
      state: Home
    - condition: state
      entity_id: input_select.arm_wakeup_alarm
      state: "P\xE5"
- action:
  - alias: ''
    data:
      message: "Juvelorkid\xE9 | vardagsrum"
      title: Please water me!
    service: notify.pushbullet
  alias: Flower | Vardagsrum | Juvelorkide
  id: '1495725269130'
  trigger:
  - below: '10'
    entity_id: sensor.flower_1_moisture
    platform: numeric_state
- action:
  - alias: ''
    data:
      message: "Juvelorkid\xE9 | sovrum"
      title: Please water me!
    service: notify.pushbullet
  alias: Flower | Sovrum | Juvelorkide
  id: '1495725269131'
  trigger:
  - below: '10'
    entity_id: sensor.flower_2_moisture
    platform: numeric_state
- action:
  - alias: ''
    data:
      message: Chili | vardagsrum
      title: Please water me!
    service: notify.pushbullet
  alias: Flower | Vardagsrum | Chili
  id: '1495725269130'
  trigger:
  - below: '10'
    entity_id: sensor.flower_3_moisture
    platform: numeric_state
- action:
  - service: zwave.heal_network
  alias: Z-wave | Heal
  id: '1496477445434'
  trigger:
  - platform: time
    after: '2:31:00'
- action:
  - service: script.sonos_stereo_on
  alias: Sonos | Vardagsrum | Start stereo
  id: '1496478237477'
  trigger:
  - entity_id: media_player.vardagsrum_musik
    platform: state
    to: playing
- action:
  - service: script.sonos_stereo_off
  alias: Sonos | Vardagsrum | Stereo off (idle)
  id: '1496478400400'
  trigger:
  - entity_id: media_player.vardagsrum_musik
    platform: state
    to: idle
- action:
  - service: script.sonos_stereo_off
  alias: Sonos | Vardagsrum | Stereo off (pause)
  id: '1496478447779'
  trigger:
  - entity_id: media_player.vardagsrum_musik
    platform: state
    to: paused
- action:
  - service: shell_command.sonos_control_shuffle_off
  - service: shell_command.sonos_volume_8
  - service_template: 'shell_command.sonos_favorite_{{states.input_select.sonos_favorites.state.lower().replace("
      ", "").replace("-", "")}}

      '
  alias: Sonos | Play favorite
  id: '1496478661322'
  trigger:
  - entity_id: input_select.sonos_favorites
    platform: state
- action:
  - service: shell_command.sonos_control_shuffle_off
  - service: shell_command.sonos_volume_8
  - service_template: >
      shell_command.sonos_playlist_{{states.input_select.sonos_playlist.state.lower().replace(" ", "").replace("-", "")}}
  alias: Sonos | Play playlist
  id: '1496478802292'
  trigger:
  - entity_id: input_select.sonos_playlist
    platform: state
