homeassistant:
  #https://materialdesignicons.com/
  #https://gist.github.com/CCOSTAN/9934de973a293b809868
  # Name of the location where Home Assistant is running
  name: Översikt
  # Location required to calculate the time the sun rises and sets
  latitude: 59.344164
  longitude: 18.055501
  # Impacts weather/sunrise data
  elevation: 26
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named extraconfig/customize

# Enables the frontend
frontend:

http:
  api_password: !secret http_password

# Checks for available updates
updater:

recorder:
  # Delete events and states older than 2 weeks
  purge_days: 7

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

ios:

config:

logger: !include extraconfig/standalonefiles/logger.yaml

# Build-in editor
automation: !include automations.yaml


ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

# Merge named
group: !include_dir_merge_named extraconfig/groups
automation old: !include_dir_list extraconfig/automation
input_select: !include_dir_merge_named extraconfig/input_select
shell_command: !include_dir_merge_named extraconfig/shell_command
script: !include_dir_merge_named extraconfig/scripts


# Merge list
sensor: !include_dir_merge_list extraconfig/sensors
binary_sensor: !include_dir_merge_list extraconfig/binary_sensors
light: !include_dir_merge_list extraconfig/light


# Dir list
#scene: !include_dir_list extraconfig/scenes


# Plain import
mqtt: !include extraconfig/standalonefiles/mqtt.yaml
zwave: !include extraconfig/standalonefiles/zwave.yaml
device_tracker: !include extraconfig/standalonefiles/device-tracker.yaml
zone: !include extraconfig/standalonefiles/zones.yaml
#binary_sensor: !include extraconfig/standalonefiles/binary_sensor.yaml
media_player: !include extraconfig/standalonefiles/media_player.yaml
switch: !include extraconfig/standalonefiles/switch.yaml
panel_iframe: !include extraconfig/standalonefiles/panel_iframe.yaml
camera: !include extraconfig/standalonefiles/camera.yaml
#weblink: !include extraconfig/standalonefiles/weblink.yaml
tellduslive: !include extraconfig/standalonefiles/tellduslive.yaml
notify: !include extraconfig/standalonefiles/notify.yaml
#ifttt: !include extraconfig/standalonefiles/ifttt.yaml
#light: !include extraconfig/standalonefiles/hue.yaml
google: !include extraconfig/standalonefiles/googlecalendar.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
#keyboard_remote: !include extraconfig/standalonefiles/keyboard_remote.yaml



