homeassistant:
  name: Översikt
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named extraconfig/customize
  packages: !include_dir_named extraconfig/packages


http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5


panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include extraconfig/standalonefiles/floorplan.yaml


updater:
  include_used_components: true


ffmpeg:
  ffmpeg_bin: /usr/bin/avconv


frontend:
discovery:
sun:
ios:
config:
python_script:


automation: !include automations.yaml
logger: !include extraconfig/standalonefiles/logger.yaml


group: !include_dir_merge_named extraconfig/groups
input_boolean: !include_dir_merge_named extraconfig/input_boolean
input_select: !include_dir_merge_named extraconfig/input_select
shell_command: !include_dir_merge_named extraconfig/shell_command
script: !include_dir_merge_named extraconfig/scripts



binary_sensor: !include_dir_merge_list extraconfig/binary_sensors
light: !include_dir_merge_list extraconfig/light
sensor: !include_dir_merge_list extraconfig/sensors


scene: !include_dir_list extraconfig/scenes


camera: !include extraconfig/standalonefiles/camera.yaml
device_tracker: !include extraconfig/standalonefiles/device-tracker.yaml
google: !include extraconfig/standalonefiles/googlecalendar.yaml
media_player: !include extraconfig/standalonefiles/media_player.yaml
mqtt: !include extraconfig/standalonefiles/mqtt.yaml
notify: !include extraconfig/standalonefiles/notify.yaml
panel_iframe: !include extraconfig/standalonefiles/panel_iframe.yaml
switch: !include extraconfig/standalonefiles/switch.yaml
tellduslive: !include extraconfig/standalonefiles/tellduslive.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
zone: !include extraconfig/standalonefiles/zones.yaml
zwave: !include extraconfig/standalonefiles/zwave.yaml


#  binary_sensor: !include extraconfig/standalonefiles/binary_sensor.yaml
#  weblink: !include extraconfig/standalonefiles/weblink.yaml
#  ifttt: !include extraconfig/standalonefiles/ifttt.yaml


