homeassistant:
  #https://materialdesignicons.com/
  #https://gist.github.com/CCOSTAN/9934de973a293b809868
  # Name of the location where Home Assistant is running
  name: Översikt
  # Location required to calculate the time the sun rises and sets
  latitude: 59.344164
  longitude: 18.055501
  # Impacts weather/sunrise data
  elevation: 26
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named extraconfig/customize

# Enables the frontend
frontend:

http:
  api_password: !secret http_password

# Checks for available updates
updater:
  include_used_components: true

#recorder:
  # Delete events and states older than 2 weeks
#  purge_days: 7

# Discover some devices automatically
discovery:

#  Enables support for tracking state changes over time.
#  history:

#  View all events in a logbook
#  logbook:

#  Track the sun
sun:

#  Enable ios app support
ios:

config:

panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml



#  Add support for built-in automation editor
automation: !include automations.yaml

#  Logging settings
logger: !include extraconfig/standalonefiles/logger.yaml

#  Used for webcam support
ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

#  Merge named
group: !include_dir_merge_named extraconfig/groups
input_select: !include_dir_merge_named extraconfig/input_select
shell_command: !include_dir_merge_named extraconfig/shell_command
script: !include_dir_merge_named extraconfig/scripts

#  Merge list
binary_sensor: !include_dir_merge_list extraconfig/binary_sensors
light: !include_dir_merge_list extraconfig/light
sensor: !include_dir_merge_list extraconfig/sensors

#  Dir list
scene: !include_dir_list extraconfig/scenes

#  Plain import | enabled
camera: !include extraconfig/standalonefiles/camera.yaml
device_tracker: !include extraconfig/standalonefiles/device-tracker.yaml
google: !include extraconfig/standalonefiles/googlecalendar.yaml
media_player: !include extraconfig/standalonefiles/media_player.yaml
mqtt: !include extraconfig/standalonefiles/mqtt.yaml
notify: !include extraconfig/standalonefiles/notify.yaml
panel_iframe: !include extraconfig/standalonefiles/panel_iframe.yaml
switch: !include extraconfig/standalonefiles/switch.yaml
tellduslive: !include extraconfig/standalonefiles/tellduslive.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
zone: !include extraconfig/standalonefiles/zones.yaml
zwave: !include extraconfig/standalonefiles/zwave.yaml

#  Plain import | disabled
#  binary_sensor: !include extraconfig/standalonefiles/binary_sensor.yaml
#  weblink: !include extraconfig/standalonefiles/weblink.yaml
#  ifttt: !include extraconfig/standalonefiles/ifttt.yaml


