alias: Flower 1
trigger:
  platform: numeric_state
  entity_id: sensor.flower_1_moisture
  below: 10
action:
  service: notify.pushbullet
  data:
    message: "Juvelorkidé | vardagsrum"
    title: "Please water me!"
