- platform: command_line
  command: !secret camera_url
  name: 'camera_controller_online_shell'


- platform: template
  sensors:
    camera_controller_online:
      friendly_name: 'Kamera Vardagsrum'
      value_template: >-
        {% if '1 received' in states('sensor.camera_controller_online_shell') %}
          On
        {%- else -%}
          Off
        {%- endif %}

