- platform: miflora
  mac: C4:7C:8D:61:3C:D9
  name: Flower 1
  force_update: false
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity

- platform: miflora
  mac: C4:7C:8D:61:3C:DC
  name: Flower 2
  force_update: false
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity

- platform: miflora
  mac: C4:7C:8D:61:7E:CC
  name: Flower 3
  force_update: false
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity

