- platform: command_line
  scan_interval: 5
  command: /usr/bin/curl --silent GET http://192.168.0.140:5005/kitchen/state | python -c 'import sys, json; print json.load(sys.stdin)["playbackState"]'
  name: 'sonos_kitchen_state_shell'

- platform: template
  sensors:
    sonos_kitchen_state:
      friendly_name: 'Sonos: Kök'
      value_template: >-
        {% if 'PLAYING' in states('sensor.sonos_kitchen_state_shell') %}
          Playing
        {%- else -%}
          Paused
        {%- endif %}
      icon_template: >-
        {% if 'PLAYING' in states('sensor.sonos_kitchen_state_shell') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
