
default_view:
  view: yes
  entities:
#  - sensor.sonos_kitchen_state
  - device_tracker.patrik_iphone
  - updater.updater
  - sensor.forecastio_apparent_temperature
  - sensor.forecastio_hourly_summary
  - group.temperatures
  - group.mediaplayer_mini
#  - group.lights
#  - group.vardagsrumstak
#  - group.sovrumstak
  - group.systemstates


### VARDAGSRUM
vardagsrum:
  view: yes
  icon: mdi:emoticon-happy
  entities:
  - group.vardagsrum_tak
  - group.vardagsrum_switchar
  - light.koksbord
  - group.vardagsrum_media
  - group.vaxt1


### SOVRUM
sovrum:
  view: yes
  icon: mdi:hotel
  entities:
  - group.sovrum_lights
  - group.sovrum_switchar
  - group.vaxt2


### KITCHEN
kitchen:
  view: yes
  icon: mdi:food-variant
  name: "Kök"
  entities:
  - group.kitchen_switchar
  - light.kokslampa

### HALL
hallway:
  view: yes
  icon: mdi:glassdoor
  name: "Hall"
  entities:
  - group.hall_switchar

### Badrum
bathroom:
  view: yes
  icon: mdi:scale-bathroom
  name: "Badrum"
  entities:
    - media_player.badrum




automation:
  name: "Automatisering"
  icon: mdi:apple-keyboard-command
  view: yes
  entities:
  - group.scripts
#  - script.wake_up
#  - script.sleep_time
#  - script.arrive_home
#  - script.left_home

#controlmusic:
#  name: "Musik"
#  view: yes
#  entities:
#  - media_player.kitchen
#  - group.mysonos
#  - group.switch_other

security_monitor:
  name: "Monitor"
  icon: mdi:camera
  view: yes
  entities:
  - group.camera1

misc_weathercenter:
  name: "Väder"
  icon: mdi:weather-sunny
  view: yes
  entities:
  - group.weatherbasics


system:
  name: "System"
  view: yes
  icon: mdi:monitor-multiple
  entities:
  - group.system_sensors
  - switch.webcam
  - group.system_arm
  - group.system_wan_stats
  - group.debug_sethomeaway
  - group.zwavedebug


