
default_view:
  view: yes
  entities:
  - sensor.sonos_kitchen_state
  - device_tracker.patrik_iphone
  - updater.updater
  - sensor.forecastio_apparent_temperature
  - sensor.forecastio_hourly_summary
  - group.temperatures
  - group.mediaplayer_mini
#  - group.lights
#  - group.vardagsrumstak
#  - group.sovrumstak
  - group.systemstates


### VARDAGSRUM
vardagsrum:
  view: yes
  entities:
  - group.vardagsrum_tak
  - group.vardagsrum_switchar
  - group.vardagsrum_media
  - group.vaxt1


### SOVRUM
sovrum:
  view: yes
  entities:
  - group.sovrum_lights
  - group.sovrum_switchar
  - group.vaxt2


### KITCHEN
kitchen:
  view: yes
  name: "Kök"
  entities:
  - group.kitchen_switchar

### HALL
hallway:
  view: yes
  name: "Hall"
  entities:
  - group.hall_switchar





automation:
  name: "Automatisering"
  view: yes
  entities:
  - group.scripts
#  - script.wake_up
#  - script.sleep_time
#  - script.arrive_home
#  - script.left_home

#controlmusic:
#  name: "Musik"
#  view: yes
#  entities:
#  - media_player.kitchen
#  - group.mysonos
#  - group.switch_other

security_monitor:
  name: "Monitor"
  view: yes
  entities:
  - group.camera1

misc_weathercenter:
  name: "Väder"
  view: yes
  entities:
  - group.weatherbasics


system:
  name: "System"
  view: yes
  entities:
  - group.system_sensors
  - switch.webcam
  - group.system_arm
  - group.system_wan_stats
  - group.debug_sethomeaway


