alias: "A good playlist after a day at work"
trigger:
  - platform: state
    entity_id: device_tracker.patrik_iphone
    from: 'Away'
    to: 'Home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '15:00:00'
#      after: '9:00:00'
      before: '23:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
#        - sat
#        - sun
    - condition: state
      entity_id: input_select.arm_debug
      state: Av
action:
  - service: script.arrive_home
