alias: "Rise and shine"
trigger:
  platform: time
  hours: 6
  minutes: 0
  seconds: 0
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
#        - sat
#        - sun
    - condition: state
      entity_id: device_tracker.patrik_iphone
      state: Home
    - condition: state
      entity_id: input_select.arm_wakeup_alarm
      state: På
action:
  - service: script.wake_up
