alias: "Time for bed"
trigger:
  platform: time
  hours: 22
  minutes: 30
  seconds: 0
condition:
  condition: time
  weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
action:
  service: homeassistant.turn_on
  entity_id:
    - switch.sovrum

